services:
  - type: web
    name: whisper-tts-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    region: oregon  
    plan: free
    envVars:
      - key: PORT
        value: 8000
