services:
  - type: web
    name: whisper-tts-service
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port=${PORT}
    autoDeploy: true
